---
- name: Install nfs-utils (RHEL)
  become: true
  tags: ['nfs']
  ansible.builtin.dnf:
    name: "{{ nfs_common_yum }}"
    state: present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install nfs-utils (Debian)
  become: true
  tags: ['nfs']
  ansible.builtin.apt:
    name: "{{ nfs_common_apt }}"
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' or ansible_distribution == 'Pop!_OS'

- name: Ensure /etc/exports exists
  become: true
  tags: ['nfs']
  ansible.builtin.copy:
    content: ""
    dest: /etc/exports
    force: false
    group: root
    owner: root
    mode: "0644"

- name: Configure idmapd.conf
  become: true
  tags: ['nfs']
  ansible.builtin.template:
    src: idmapd.conf.j2
    dest: /etc/idmapd.conf
    mode: "0644"

- name: Copy sysconfig/nfs
  become: true
  tags: ['nfs']
  ansible.builtin.copy:
    src: nfs.sysconfig
    dest: /etc/sysconfig/nfs
    mode: "0644"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
