---
- name: Configure NFS Server
  hosts: nfs_server
  gather_facts: true
  roles:
    - {role: "nfs_server", tags: "nfs"}

- name: Configure NFS Clients
  hosts: nfs_client
  gather_facts: true
  roles:
    - {role: "nfs_client", tags: "nfs"}

- name: Configure KVM
  hosts: kvm_nodes
  gather_facts: true
  roles:
    - {role: "kvm_qemu", tags: "kvm"}
