---
- name: Install Management Server role
  hosts: mgmt_server
  gather_facts: true
  tags: ['mgmt']
  roles:
    - mgmt_server

- name: Install kvmsh to nodes
  hosts: kvm_nodes
  gather_facts: false
  tasks:
    - name: Install kvmsh..
      become: true
      ansible.builtin.copy:
        src: "{{ kvmsh_bin }}"
        dest: /usr/local/bin
        mode: "0755"
        owner: root
        group: kvm
