---
- name: Configure NFS Server
  hosts: nfs_server
  gather_facts: true
  tags: [ 'nfs' ]
  roles:
    - 'nfs-server'

- name: Configure NFS Clients
  hosts: nfs_client
  gather_facts: true
  tags: [ 'nfs' ]
  roles:
    - 'nfs-client'

- name: Configure KVM
  hosts: kvm_nodes
  gather_facts: true
  tags: [ 'nfs' ]
  roles:
    - 'kvm-qemu'
