---
- name: Configure NFS Server
  hosts: nfs_server
  gather_facts: true
  tags: ['nfs']
  roles:
    - 'nfs_server'

- name: Configure NFS Clients
  hosts: nfs_client
  gather_facts: true
  tags: ['nfs']
  roles:
    - 'nfs_client'

- name: Configure KVM
  hosts: kvm_nodes
  gather_facts: true
  tags: ['nfs']
  roles:
    - 'kvm_qemu'
