---
- name: Install EPEL Release on RHEL-based systems
  yum:
    name: 'epel-release'
    lock_timeout: 180
    state: present
  become: true
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install Mgmt Prerequisites (yum)
  yum:
    name: '{{ yum_mgmt_packages }}'
    lock_timeout: 180
    state: present
  become: true
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install Mgmt Prerequisites (apt)
  apt:
    name: '{{ apt_mgmt_packages }}'
    state: present
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Configure DnsMasq
  template:
    src: 'dnsmasq.conf.j2'
    dest: '/etc/dnsmasq.conf'
    mode: 0644
  become: true

- name: Enable and Start DnsMasq
  service:
    name: 'dnsmasq'
    state: 'started'
    enabled: 'yes'
  become: true

- name: Install kvm-mgr.sh
  copy:
    src: '{{ kvmmgr_bin }}'
    dest: '/usr/local/bin'
    mode: 0755
    owner: 'root'
    group: 'kvm'
  become: true
