---
- name: Install RHEL packages
  become: true
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

  block:
    - name: Install EPEL Release on RHEL-based systems
      ansible.builtin.dnf:
        name: epel-release
        lock_timeout: 180
        state: present
    - name: Install Mgmt Prerequisites (yum)
      ansible.builtin.dnf:
        name: "{{ mgmt_server_yum }}"
        lock_timeout: 180
        state: present
- name: Install Mgmt Prerequisites (apt)
  ansible.builtin.apt:
    name: "{{ mgmt_server_apt }}"
    state: present
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' or ansible_distribution == 'Pop!_OS'

- name: Configure DnsMasq
  ansible.builtin.template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf
    mode: "0644"
  become: true

- name: Enable and Start DnsMasq
  ansible.builtin.service:
    name: dnsmasq
    state: started
    enabled: "yes"
  become: true

- name: Install kvm-mgr.sh
  ansible.builtin.copy:
    src: "{{ kvmmgr_bin }}"
    dest: /usr/local/bin
    mode: "0755"
    owner: root
    group: kvm
  become: true
