---
- name: Restart_apparmor
  ansible.builtin.service:
    name: apparmor
    state: restarted
  become: true

- name: Restart_libvirtd
  ansible.builtin.service:
    name: libvirtd
    state: restarted
  become: true

- name: Source_sysctl
  ansible.builtin.shell: sysctl --system
  become: true
